### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Truxnell** [SQLJames/factorio-server-charts#16]
I am interested in the license you plan for this project.
I have used this chart for a little while but the design was not quite right for my needs (mainly around my loadbalancer/setup) and i ended up using a seperate service.yaml for it.

I am part of the k8s @ home community and we have a large library of helm charts based off a excelent common library.  I have setup a chart but would like to use part of your config-mapping, as it makes it so much easier to setup than expectiing users to edit config manually!

**Comment by SQLJames** [comment]
Hi truxnell, are you trying to just take up support for this in your k8s @ home repo? I've used a lot of your helm charts in the past.

**Comment by Truxnell** [comment]
Hi, Ive actually done a new chart from scratch using the k8s common library. It removes the need for almost all boilerplate code.  I've just had to pop back in some templates for creating/mounting the configmap, as I really liked the idea of being able to manage the json server config in yaml.

I have been testing it at home fine, I just used some of your yaml from the config section so I didn't have to recreate it!

**Comment by SQLJames** [comment]
I'm thinking about using the unlicense, I've not really needed to look into this before, I'd just ask that this repo is mentioned in the readme. Thoughts?

**Comment by Truxnell** [comment]
I was the same, I got asked recently about the license for my k8s repo and was rather surprised.  I will be definitely be mentioning your work for sure, so that is no issue!

**Comment by SQLJames** [comment]
I uploaded the unlicense today.
