### ISSUE TITLE
the `gamePassword` volume also breaks the lowercase RFC 1123 name requirement.

### ISSUE THREAD

**Issue by SQLJames** [SQLJames/factorio-server-charts#21]
the `gamePassword` volume also breaks the lowercase RFC 1123 name requirement. 

__Originally posted by @avanier in https://github.com/SQLJames/factorio-server-charts/pull/20#issuecomment-1312622917__

**Comment by Haloghen** [comment]
Wokring on it right now, PR to be expected soon
