### ISSUE TITLE
negative_path_cache_delay_interval missing from map-settings

### ISSUE THREAD

**Issue by roertel** [SQLJames/factorio-server-charts#4]
As of Factorio 1.1.0, `negative_path_cache_delay_interval` must be set in the `map-settings.json` (configMap). You can specify this in your `values.yaml` file, but since it's a required field in the JSON, a default value should probably be specified in the chart. More details in the Factorio [forum](https://forums.factorio.com/viewtopic.php?f=11&t=91712&p=522185&hilit=path_cache_delay#p522185).

**Comment by nippold** [comment]
@roertel I just created a PR that includes your fix too

**Comment by SQLJames** [comment]
Resolved in the pull request by @nippold
