### ISSUE TITLE
mod list needs to be url encoded

### ISSUE THREAD

**Issue by seg-falt** [SQLJames/factorio-server-charts#42]
Mod list needs to be URL encoded when there's a space in the mod name. 

without encoding:
![image](https://github.com/SQLJames/factorio-server-charts/assets/147103339/979b6b6f-636d-4d98-9586-1419786b82a2)

with encoding: 
![image](https://github.com/SQLJames/factorio-server-charts/assets/147103339/4d5d3e5d-6926-43b3-9875-c66e75af66ea)

The only relevant difference between the two deployments is the modlist:

without encoding:
![image](https://github.com/SQLJames/factorio-server-charts/assets/147103339/e6a83c43-cea2-4715-bf1a-c8af74a336c1)

with encoding:
![image](https://github.com/SQLJames/factorio-server-charts/assets/147103339/d7d90503-627a-4d58-9070-e4e9c348b666)

a `urlencode` binary is available in a gridsite package([man page](https://linux.die.net/man/1/urlencode)), or it can be done through [curl dataencode arguements](https://stackoverflow.com/a/2027690)

**Comment by SQLJames** [comment]
I believe this should just be a modification to the shell script but it's been awhile since I've looked.

I'll take a look this weekend.
