### ISSUE TITLE
Ability to Specify mod version

### ISSUE THREAD

**Issue by dstrivelli** [SQLJames/factorio-server-charts#45]
Great chart, thank you for your efforts and for providing this to the community!

With the recent "breaking changes" to SpaceExploration + Krastorio2 for mid game players, there should be an easy way to pin mods at certain versions. I had to restart my pod due to a failed blueprint import, and it pulled the latest plugin on boot that I didn't want, and now I'm seemingly needing the unofficial mods section for rolling back.

Ideally, mods can have pinned versions and have those be downloaded from the mod portal.

**Comment by SQLJames** [comment]
This is a good point, would you mind sending me the values file of before and after so I can replicate?

I believe there is a flag we can tap on the container to prevent this behavior.

**Comment by SQLJames** [comment]
removed comment for update_mods_on_start  and added to new ticket
