### ISSUE TITLE
Factorio: Space Age changes config values

### ISSUE THREAD

**Issue by Kariton** [SQLJames/factorio-server-charts#48]
With the recent release of space age the supplied configmap does no longer work.

I got changed values from here: https://github.com/wube/factorio-data
they seem to work.

i used to get an error when starting the container:
> Error Util.cpp:81: Key "asteroids" not found in property tree at ROOT

"asteroids" is a new value for "map_settings"

EDIT: formatting

**Comment by SQLJames** [comment]
There are going to be new values added from the expansion, which will need to be added to the appropriate configs. I haven't had time to sort that out yet, if you can provide those configs it would be helpful.

**Comment by henryjarend** [comment]
I got this working! Let me just create the PR and then it should be good to go!

**Comment by henryjarend** [comment]
https://github.com/SQLJames/factorio-server-charts/pull/49

**Comment by SQLJames** [comment]
Appreciate it 😀 , I am in the hospital at the moment haha, so I'll be away from a coding setup for a few days.

**Comment by Kariton** [comment]
Oh man...
I would be really frustrated.
But hey, at least all the hotpatches should be out by the time you’re back in action!
Wishing you a speedy recovery!
