### ISSUE TITLE
rcon port test intermittent failure

### ISSUE THREAD

**Issue by SQLJames** [SQLJames/factorio-server-charts#54]
When running the Chart tests the rcon port will fail intermittently on pipeline runs we need to investigate this.

**Comment by ohnoitsyou** [comment]
I have a sneaking suspicion that the reason it's failing is that the rcon pod is just coming online too quickly. I've run the chart several times locally and it always fails, but if I redeploy just the rcon pod after the server is online, it works just fine.

One option would be to delay the rcon test with a sleep of a couple seconds, but that's not necessarily super reliable.

Is there a desire to keep that test around or could a move to using liveness/readiness probes work?

**Comment by SQLJames** [comment]
I'd love for us to keep and even expand to more tests. 

Adding the probes is likely the best choice for fixing this.

**Comment by SQLJames** [comment]
fixed with 2.0.3
