### ISSUE TITLE
Ability to use `ipFamilyPolicy` on the generated svc

### ISSUE THREAD

**Issue by samip5** [SQLJames/factorio-server-charts#63]
Curently the values for service doesn't get that set.

**Comment by SQLJames** [comment]
@samip5 can you try using the branch in #65, I cant test this because I am not running dual stack but I added this support to all three of the services we have.

**Comment by samip5** [comment]
I'm not exactly sure how I would test drive it, when it's in a branch and not a published chart?

**Comment by SQLJames** [comment]
I merged it, a new release will be generated shortly for it. Just respond here if your not able to get it working 😀
