### ISSUE TITLE
server_settings values do not appear in Config Map

### ISSUE THREAD

**Issue by lukasyelle** [SQLJames/factorio-server-charts#9]
I've been struggling to get this server working in my HA Kubernetes cluster for about a week now. I just realized today that the values configuration for the `server_settings` file does not seem to be applied with the `--values values.yaml` flag. The default values from the values.yaml file in this repo do not even appear to be sent to the config map in Kubernetes. 

I've tried the following helm commands to apply my own values.yaml file which is just a modified copy of the one in this repo:
`helm install factorio sqljamesfactorio/factorio-server-charts -n factorio --values factorio/factorio-helm-values.yaml`
`helm install factorio sqljamesfactorio/factorio-server-charts -n factorio -f factorio/factorio-helm-values.yaml`
 and, because neither of those worked as expected, `helm install factorio sqljamesfactorio/factorio-server-charts -n factorio -f factorio/factorio-helm-values.yaml  --values factorio/factorio-helm-values.yaml`. 

Each way I tried did end up creating the Service as laid out in my custom values file, and set the resource requests properly, but still the `factorio-factorio-server-charts-serversettingsconfig` config map still has outdated default values in the compiled `server-settings.json` field with the following content:

`{"afk_autokick_interval":0,"allow_commands":"admins-only","auto_pause":true,"autosave_interval":10,"autosave_only_on_server":true,"autosave_slots":5,"description":"Factorio running on Kubernetes","game_password":"","ignore_player_limit_for_returning_players":false,"max_players":0,"max_upload_in_kilobytes_per_second":0,"max_upload_slots":5,"maximum_segment_size":100,"maximum_segment_size_peer_count":10,"minimum_latency_in_ticks":0,"minimum_segment_size":25,"minimum_segment_size_peer_count":20,"name":"Factorio","non_blocking_saving":false,"only_admins_can_pause_the_game":true,"password":"","require_user_verification":true,"tags":["game","tags"],"token":"","username":"","visibility":{"lan":true,"public":true}}
`

I've set a valid token, username, and the new default visibility includes public: false, which I kept in my values file, but none of those settings seem to carry over to the pod configuration. This is particularly evident due to the fact that I get the following error: `1.406 Error ServerMultiplayerManager.cpp:717: Matching server connection failed: Error when creating server game: Missing token.`

**Comment by lukasyelle** [comment]
So turns out, the values.yaml file in this repo uses `server_settings` but the deployment is looking for `serverSettings`. After updating the name of that key in the values file, the config map is applied as expected.

**Comment by lukasyelle** [comment]
Created a [PR](https://github.com/SQLJames/factorio-server-charts/pull/10) which addresses this issue

**Comment by SQLJames** [comment]
Sorry I'm not following some changes were made around the structure of the values file with the naming of that section, however, if I pull down the repo and deploy, I am able to set public: false or public: true in the config map for the game server_settings. Do you have a reference in the code that is using the old config map name?

**Comment by lukasyelle** [comment]
You make a good point @SQLJames, I cannot find any mention of the serverSettings name in the code on GitHub. Unfortunately however, when using Helm (I’ve run `helm update`) the only way I’ve been able to get those variables to overwrite the defaults is to use the camel-case syntax as outlined in the readme. I will try running the chart with the code I have locally instead of pulling from helm and see if that changes anything. Do you have any ideas as to what could be causing this?

**Comment by lukasyelle** [comment]
As an update I'm not sure what changed but after all this time it seems to work through helm. I haven't the finest idea as to why it works now but didnt before with the `server_settings` key, but I'll take it. Closing this issue and associated PR, my appologies @SQLJames.
